addresses = {
    "Bitcoin (BTC)": "1LQSzFZKE5vwiUS94toMG7r5M2nQ4X2muw",
    "Bitcoin Cash (BCH)": "bitcoincash:qzhr6lc9r64c3wg3jnndqaxzpyxeghdp2s57w5wgwu",
    "Bitcoin Gold (BTG)": "GJbYu4YviyCi8azMV6ZAvdhjJTcigdmnPV",
    "Dash (DASH)": "Xn5HwktiWJfgKydTDjodBTjJDA6tVxzAho",
    "DigiByte (DGB)": "D97CQ5pV1AukRY1FJTSW3CFkJtUZgdwJq4",
    "Dogecoin (DOGE)": "D5YP7CggUUkS3fu1B7RjhjJ7jvNu6A4Ksx",
    "Ethereum (ETH)": "0x80D3CA7528cF05118131dBa3d7852Db2685c4b9E",
    "Firo (FIRO)": "a5R3Z4XBjj9oQS6kMgtfT5kMYMnA8Qx2Ga",
    "Komodo (KMD)": "RQzp2jDRhRMrzBJZobGtUQhkQfcnfXdxWz",
    "Litecoin (LTC)": "LRQ6TBVXsEVPApbCY79bV1d9LR8E7JiuDd",
    "Qtum (QTUM)": "QXFD7QitfegWXf4n4F9bVLU9HXqESgRVWq",
    "Ravencoin (RVN)": "RLMJbB268ayzGtJokjimNiLgdAccF8yv21",
    "Reddcoin (RDD)": "RvawiN6Ues4gxdu52JkKLQ7cKYSDDYwkUQ",
    "Verge (XVG)": "DKY9rZfiw6qShLvWzKZCmuKJdiadDyhnVr",
    "Vertcoin (VTC)": "VmLS1YQuRVJT73ZkQyQNKWUPUCEsC95MSJ",
    "Zcash (ZEC)": "t1gFJup6Mri4mZ1Pgqgzqmz2a3hg66Cpyga",
}
urls = {
    "Bitcoin (BTC)": "https://bitcoinblockexplorers.com/tx/",
    "Bitcoin Cash (BCH)": "https://bchblockexplorer.com/tx/",
    "Bitcoin Gold (BTG)": "https://btgexplorer.com/tx/",
    "Dash (DASH)": "https://dashblockexplorer.com/tx/",
    "DigiByte (DGB)": "https://digibyteblockexplorer.com/tx/",
    "Dogecoin (DOGE)": "https://dogeblocks.com/tx/",
    "Ethereum (ETH)": "https://ethblockexplorer.org/tx/",
    "Firo (FIRO)": "https://firoblockexplorers.com/tx/",
    "Komodo (KMD)": "https://komodoblockexplorer.com/tx/",
    "Litecoin (LTC)": "https://litecoinblockexplorer.net/tx/",
    "Qtum (QTUM)": "https://qtumblockexplorer.com/tx/",
    "Ravencoin (RVN)": "https://rvnblockexplorer.com/tx/",
    "Reddcoin (RDD)": "https://rddblockexplorer.com/tx/",
    "Verge (XVG)": "https://xvgblockexplorer.com/tx/",
    "Vertcoin (VTC)": "https://vtcblocks.com/tx/",
    "Zcash (ZEC)": "https://zecblockexplorer.com/tx/"
}
# List of cryptocurrency names
cryptos = {
    "Bitcoin (BTC)": "Payment/Photos/bitcoin (btc).png",
    "Bitcoin Cash (BCH)": "Payment/Photos/bitcoin cash (bch).png",
    "Bitcoin Gold (BTG)": "Payment/Photos/bitcoin gold (btg).png",
    "Dash (DASH)": "Payment/Photos/dash (dash).png",
    "DigiByte (DGB)": "Payment/Photos/digibyte (dgb).png",
    "Dogecoin (DOGE)": "Payment/Photos/dogecoin (doge).png",
    "Ethereum (ETH)": "Payment/Photos/ethereum (eth).png",
    "Firo (FIRO)": "Payment/Photos/firo (firo).png",
    "Komodo (KMD)": "Payment/Photos/komodo (kmd).png",
    "Litecoin (LTC)": "Payment/Photos/litecoin (ltc).png",
    "Qtum (QTUM)": "Payment/Photos/qtum (qtum).png",
    "Ravencoin (RVN)": "Payment/Photos/ravencoin (rvn).png",
    "Reddcoin (RDD)": "Payment/Photos/reddcoin (rdd).png",
    "Verge (XVG)": "Payment/Photos/verge (xvg).png",
    "Vertcoin (VTC)": "Payment/Photos/vertcoin (vtc).png",
    "Zcash (ZEC)": "Payment/Photos/zcash (zec).png",
}
