custom_texts = [
    "Select coin",
    "Choose a digital currency to pay:",
    "No coin selected!",
    "You need to choose a digital currency to move on to the next step.",
    "Payment",
    "Pay before time's up!",
    "Address",
    "Price",
    "Input your Transaction Hash ID (TXID):",
    "Address error",
    "Your payment receipt was sent to another address and is not acceptable.",
    "Price error",
    "You haven't paid exact price! Pay the amount not less or more before time runs out and enter its TXID.",
    "TXID error",
    "Your transaction ID does not exist! Copy the transaction ID and then enter it in the desired place.",
    "Date error",
    "Your payment receipt was registered on another date and is not acceptable.",
    "Time error",
    "Your payment receipt was registered at another time and is not acceptable.",
    "Connection error",
    "The Internet connection is lost! Try again or contact support in the [about] section.",
    "Empty TXID",
    "First, enter the TXID and then proceed to verify the purchase.",
    "Help",
    "Once you know the price, go to your cryptocurrency account. Pay the price in that selected digital currency. After that, you must copy your payment's transaction hash ID (TXID). Then, go back to the program and paste the [TXID] in the bottom part. Press [Buy] button before time's up!",
    "Use a newer version",
    "This payment method is not working anymore! Please download a new version of this program or contact the support section.",
    "Digital currency error",
    "Currently, payment with this digital currency is not possible. Choose another digital currency to pay.",
    "Bought",
    "Congratulations!",
    "Your purchase was successful.",
    "Now you can use all the features of this program.",
    "You paid before!",
    "You don't need to pay again! You already bought this!",
]
